.TH BÉPO 1 "21 July 2014"
.SH NOM
BÉPO /- Disposition de clavier francophone ergonomique fondée sur la méthode dvorak

.SH CARTES
.SS Carte simplifiée
┌────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────╔════════╗
│    │    │    │    │    │    │    │    │    │    │    │    │    ║        ║
│  $ │  " │  « │  » │  ( │  ) │  _ │  + │  - │  / │  * │  = │  % ║ <--    ║
╔════╧══╗─┴──┬─┴──┬─┴──┬─┴──┬─┴──┬─┴──┬─┴──┬─┴──┬─┴──┬─┴──┬─┴──┬─╚══╦═════╣
║  |<-  ║    │    │    │    │    │    │    │    │    │    │    │    ║   | ║
║  ->|  ║  B │  É │  P │  O │  È │  ^ │  V │  D │  L │  J │  Z │  W ║ <-' ║
╠═══════╩╗───┴┬───┴┬───┴┬───┴┬───┴┬───┴┬───┴┬───┴┬───┴┬───┴┬───┴┬───╚╗    ║
║        ║    │    │    │    │    │    │    │    │    │    │    │    ║    ║
║  CAPS  ║  A │  U │  I │  E │  , │  C │  T │  S │  R │  N │  M │  Ç ║    ║
╠══════╦═╝──┬─┴──┬─┴──┬─┴─══─┴──┬─┴──┬─┴─══─┴──┬─┴──┬─┴──┬─┴──╔═╧════╩════╣
║   ^  ║    │    │    │    │    │    │    │    │    │    │    ║     ^     ║
║   |  ║  Ê │  À │  Y │  H │  . │  K │  ' │  Q │  G │  X │  F ║     |     ║
╠══════╩╦═══╧══╦═╧═══╦╧════╧════╧════╧════╧════╧═╦══╧══╦═╧════╬═════╦═════╣
║       ║      ║     ║ NBSPACE      FINE-NBSPACE ║     ║      ║     ║     ║
║ Ctrl  ║ WinG ║ Alt ║ SPACE                     ║AltGr║ WinD ║WinM ║ Ctrl║
╚═══════╩══════╩═════╩═══════════════════════════╩═════╩══════╩═════╩═════╝

.SS Carte complète
┌────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────╔═════════╗
│ # ¶│ 1 „│ 2 “│ 3 ”│ 4 ≤│ 5 ≥║ 6  │ 7 ¬│ 8 ¼│ 9 ½│ 0 ¾│ ° ′│ ` ″║         ║
│ $ –│" ––│ « <│ » >│ ( [│ ) ]║ @ ^│ + ±│ - −│ / ÷│ * ×│ = ≠│ % ‰║ <--     ║
╔════╧══╗─┴──┬─┴──┬─┴──┬─┴──┬─┴──┬─┴──┬─┴──┬─┴──┬─┴──┬─┴──┬─┴──┬─╚══╦══════╣
║  |<-  ║ B ¦│ É ˝│ P §│ O Œ│ È `║ !  │ V  │ D Ð│ L  │ J Ĳ│ Z Ə│ W  ║   |  ║
║  ->|  ║ b |│ é ´│ p &│ o œ│ è `║ ˆ ¡│ v ˇ│ d ð│ l /│ j ĳ│ z ə│ w ˘║ <-'  ║
╠═══════╩╗───┴┬───┴┬───┴┬───┴┬───┴┬───┴┬───┴┬───┴┬───┴┬───┴┬───┴┬───╚╗     ║
║        ║ A Æ│ U Ù│ I ˙│ E ¤│ ; ̛║ C ſ│ T Þ│ S  │ R ™│ N  │ M º│ Ç ,║     ║
║  CAPS  ║ a æ│ u ù│ i ¨│ e €│ , ’║ c ©│ t þ│ s ß│ r ®│ n ˜│ m ¯│ ç ¸║     ║
╠══════╦═╝──┬─┴──┬─┴──┬─┴─══─┴──┬─┴──┬─┴─══─┴──┬─┴──┬─┴──┬─┴──╔═╧════╩═════╣
║   ^  ║ Ê  │ À  │ Y ‘│ X ’│ : ·│ K  ║ ?  │ Q  │ G  │ H ‡│ F ª║     ^      ║
║   |  ║ ê /│ à \│ y {│ x }│ . …│ k ~║ ' ¿│ q °│ g µ│ h †│ f ˛║     |      ║
╠══════╩╦═══╧══╦═╧═══╦╧════╧════╧════╧════╧════╧═╦══╧══╦═╧════╬═════╦══════╣
║       ║      ║     ║ insécable   fine insécable║     ║      ║     ║      ║
║ Ctrl  ║ WinG ║ Alt ║ SPACE        _            ║AltGr║ WinD ║WinM ║ Ctrl ║
╚═══════╩══════╩═════╩═══════════════════════════╩═════╩══════╩═════╩══════╝

Sur cette carte, chaque touche est représenté par un caré qui délimite les symbole qu’elle produit. En sachant que sur ce carré, le symbole représenté en bas à gauche est indique le caractère produit en accès dirrecte, c’est à dire par appuis simple sur cette touche ; le symbole en bas à droite indique le carctère produit par la combinaison d’AltGr et de la dite touche ; le symbole en haut à gauche est celui produit par la combinaison de la touche Maj et de la touche en question ; et que le caractère en haut à droite est indique le symbole produit par la double combinaison de la touche Maj et d’AltGr sur la dite touche.

┌────┐
│ A Æ│
│ a æ│
└────┘

Cette touche, par exemple, est la n-ième du clavier. Le "a" y est en accès dirrecte, l’"æ" en AltGR, l’"A" en Maj et l’"Æ" en AltGR+Maj.

.SH DESCRIPTION
BÉPO est une disposition de clavier ergonomique destinée à l’utilisation de la langue française et optimisée pour les clavier 102touches  européen mais compatible avec les claviers américains
.
Son élaboration, fondée sur les principes d’Auguste Dvorjak, tient compte de la fréquence d’apparition des caractères en langue française mais aussi dans les activités anexes des francophones
 comme la programmation. Ainsi, les touches les plus utilisées se retrouvent majoritairement sur la ligne de repos. De plus, la disposition BÉPO permet une alternance des caractères fréquemme
nt accolés, rendant plus simple la saisie des digrammes.

En tant que disposition destinée à l’usage des francophones, BÉPO simplifie l’accès aux symboles nécessaires à la langue française dans le soucis d’une typographie soignée.
Ainsi, les caractères « é », « è », « ê », « à », « ç » se trouvent en accès directe, de même que leur majuscules « É », « È », « Ê », « À », « Ç » sont accessible par simple pression sur SHI
FT.
L’accès aux symboles annexes aussi s’en retrouve simplifié. Par exemple, les guillemets français de premier niveau “«»”, ou de second niveau « “” », le tiret quadratin « — » sont en accès dir
ecte.
Par ailleurs, la disposition BÉPO ne néglige pas l’usage de langues étrangères que peut avoir un francophones, c’est pourquoi il est possible de produire tous les caractères en usage dans tou
tes les langues de l’Union européenne ainsi que les caractères spécifiques au Turque et à l’Azery. Il est même possible, moyennant une configuration (Voir ci-dessous), d’inclure à BÉPO un mod
ificateur grecque qui donne l’accès à tout l’alphabet grec.

Ainsi, BÉPO est particulièrement adapté aux francophones et utilisateur massifs du français. Néanmoins, l’efficacité de cette disposition n’est atteinte que pour l’utilisation à laquelle elle
 a été prévue c’est à dire la frappe à l’aveugle à dix doigts.

La dispositon BÉPO est déstinée aux individus ayant l’usage et la pleine motricité de leurs deux mais et dix doigts. Pour les personnes ne remplissant pas ces conditions, voir les projets con
curents.

.SH TERMINOLOGIE

.SH ACTIVATION DANS X.org
Pour X.org, La disposition bépo s’active par la commande "setxkbmap fr bepo".

BÉPO peut être activée par défaut dès l’ouverture d’un gestionnaire de bureau.

.SS Gnome 2.x
Allez dans le menu « Système → Préférences → Clavier → [onglet] Agencements → [bouton] Ajouter… »
Vous devriez y trouver votre nouvelle disposition dans la section « France », sous l’une des dénominations « Bepo, ergonomic, dvorak way ».
Pour que le clavier BÉPO soit le choix par défaut, faites un glissé-déposé du nom pour le mettre en premier ou utilisez le bouton « Vers le haut ».
Validez, le clavier est actif.

.SS KDE
Dans « (Centre de) Configuration → Régionalisation et accessibilité → Disposition du clavier », cochez la case « Activer les dispositions du clavier » si ce n’est déjà le cas. Sélectionnez « 
France fr », cliquez sur le bouton « Ajouter >> » et choisssez la variante « bepo » dans la liste déroulante.


.SH ACTIVATION DANS LA CONSOLE Linux
La configuration de clavier pour la console se trouve dans l’archive http://download.tuxfamily.org/dvorak/keymaps/fr-dvorak-bepo-keymaps-1.0rc2.tgz

En tant que root (super-utilisateur) il faut saisir la commande :
.RS
loadkeys fr-dvorak-bepo.kmap
.RE
Ce qui a pour effet de basculer le clavier en disposition fr-dvorak-bépo

Pour que la disposition soit accessible de n’importe quel répertoire et pour n’importe quel utilisateur, il faut copier le fichier fr-dvorak-bepo.kmap dans l’un des répertoires :

.RS
        /usr/lib/kbd/keymaps/i386/dvorak/
        /lib/kbd/keymaps/i386/dvorak/ sur Fedora
        /usr/share/keymaps sur debian
        /usr/share/kbd/keymaps/i386/dvorak sur archlinux
        /usr/share/keymaps/i386/dvorak/ sous Gentoo
.RE

Dès lors, tout utilisateur pourra basculer en BÉPO avec la commande :
.RS
loadkeys fr-dvorak-bepo
.RE

Il pourra, s’il le desir, revenir par la suite à une disposition AZERTY par :
.RS
loadkeys fr
.RE


.SS Debian
Sous Debian, le paquet "console-data" contient déjà la disposition BÉPO. Pour l’installer, il suffit de saisir :
.RS
sudo aptitude install console-data
sudo loadkeys dvorak-fr-bepo
Le fichier associé se situe alors dans /usr/share/keymaps/i386/dvorak/dvorak-fr-bepo.kmap.gz
.RE

.SS Archlinux
Vous pouvez installer BÉPO en installant le paquet nomé "bepo-keymaps" :
.RS
pacman -S bepo-keymaps
.RE

.SH UTILISATION
Après avoir activé la disposition BÉPO et affin de tirrer au mieux l’avantage érgonomique, il est important de l’utilisée de la façon pour laquelle elle a été conçue.

.SH APPRENTISSAGE

.SH CARACTÈRES PRIS EN CHARGE
Les caractères listés ici sont en accès direct, aux niveaux majuscule ou AltGr, selon leur fréquence respective. Beaucoup sont accessibles avec une ou plusieurs touches mortes.

Sous GNU/Linux, certaines touches mortes supplémentaires sont disponibles via l’ajout d’une touche compose.

Les caractères non disponibles mais prévus sont marqués d’un astérisque « * ».

.SS Tous ceux des claviers azerty
Les 142 caractères présents sur les claviers azerty français

.RS
44 majuscules et 47 minuscules : A a À à Â â Ä ä Ã ã B b C c ç D d E e é È è Ê ê Ë ë F f G g H h I i Ì ì Î î Ï ï J j K k L l M m N n Ñ ñ O o Ò ò Ô ô Ö ö Õ õ P p Q q R r S s T t U u Ù ù Û û Ü ü V v W w X x Y y ÿ Z z ;
.RE

.RS
30 symboles typographiques : _ - ' . , ; : ! ? @ & § ~ ^ ` ¨ ° | ( ) { } [ ] / \ < > " # ;
.RE

.RS
16 chiffres, opérations : 0 1 2 3 4 5 6 7 8 9 ² * + = % µ ;
.RE

.RS
4 unités monétaires : € $ ¤ £ ;
.RE

.RS
1 espace ;
.RE

les 13 caractères supplémentaires du clavier azerty belge :´ Á á É Í í Ó ó Ú ú Ý ý ³ ;

.SS La disposition inclut également
Les 15 caractères nécéssaires à une composition soignée en français, sans terme étranger

les 84 lettres et 6 symboles supplémentaires des 21 langues officielles de l’Union européenne utilisant l’alphabet latin

les caractères suivants, utilisables pour une composition très soignée : · ± × ÷ † ‡ ′ ″ ` • ‹ › ‿ ⁂ ; 

d’autres caractères pouvant être utiles : ¶ ¦ ¬ © ® ™ ª º ♯ ♮ ♭ ;

les lettres des langues suivantes non mentionnées ci-dessus : 

les lettres du grec monotonique, très utilisées dans les domaines techniques : Α Β Δ Ε Φ Γ Η Ι Θ Κ Λ Μ Ν Ο Π Χ Ρ Σ Τ Υ Ω Ξ Ψ Ζ α β δ ε φ γ η ι θ κ λ μ ν ο π χ ρ σ τ υ ω ξ ψ ζ (sans les variantes ϐ ϵ ϴ ϑ ϰ ϖ ϱ ς ϒ ϕ).

les symboles monétaires : ฿ ₵ ¢ ₡ ₫ € ƒ ₲ ₴ ₭ £ ₤ ₥ ₦ ₱ ₨ ৲ ৳ 元 圓 $ ₪ ₮ ₩ ¥ ₳ ₢ ₰ ₯ ₠ ₣ ℳ ₧

les caractères de l’alphabet phonétique international utilisés pour les langues ci-dessus ;

les caractères désuets des langues à script roman en Europe : ĸ ſ ƶ Ƶ ;

les lettres des langues et transcriptions suivantes : 


.SH EXTENSION DU CHAMP DES POSSIBILITÉS


.SH PROBLÈMES CONNUS


.SH VOIR AUSSI


.SH AUTEUR
Fauve (Aka Idriss al Idrissi), communauté BÉPO <http://bépo.fr>, <mailto:fauve [POINT] ordinator [AROBASE] taniere [POINT] info>.
